import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import AppNavbar from './components/AppNavbar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="">
                    <AppNavbar />
                    <Navbar />
                    <main className="container min-h-screen w-screen pt-48">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
